# Generated by Django 2.2.7 on 2019-11-10 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='time',
            field=models.TimeField(auto_now_add=True),
        ),
    ]
