# Generated by Django 2.2.7 on 2019-11-10 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20191110_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='parking',
            name='left',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='parking',
            name='paid',
            field=models.BooleanField(default=False),
        ),
    ]
